### ISSUE TITLE
replace in workflow echo ... >> $GITHUB_OUTPUT using Environment Files

### ISSUE THREAD

**Issue by sl5net** [sl5net/autocivp#51]
`set-output` being deprecated

**Addressing the `set-output` Deprecation:**

**The Problem:**

You're currently using this pattern to set output variables:

```bash
echo "VARIABLE_NAME=value" >> $GITHUB_OUTPUT
```

**The Solution: Use Environment Files**

Instead of writing to `$GITHUB_OUTPUT`, you need to write to a dynamically generated file path provided by the `$GITHUB_ENV` environment variable.

**Here's how to update your workflow:**

1.  **Modify the `run:` scripts:** Replace all instances of `echo "VARIABLE_NAME=value" >> $GITHUB_OUTPUT` with:

    ```bash
    echo "VARIABLE_NAME=value" >> $GITHUB_ENV
    ```

    *   `$GITHUB_ENV` is an environment variable that contains the path to a file where you can set environment variables for subsequent steps.

2.  **Update Your Steps:** The steps where you currently have the `echo` command will need to be updated.

**Example:**

Let's take the `Get Version from mod.json` step:

**Old Code:**

```yaml
      - name: Get Version from mod.json
        id: get_version
        run: |
          VERSION=$(jq -r .version mod.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
```

**New Code:**

```yaml
      - name: Get Version from mod.json
        id: get_version
        run: |
          VERSION=$(jq -r .version mod.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

```

**Apply the Change to All Relevant Steps:**

You'll need to apply this change to all steps in your workflow that are currently using `echo ... >> $GITHUB_OUTPUT`:

*   `Get Version from mod.json`
*   `Calculate Release Version and Tag`
*   `Check if Tag Exists`
